# Project information
site_name: Gluu Server 3.1.0 Docs
site_description: Documentation for Gluu Server

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-gluu-server-prod
repo_url: https://github.com/GluuFederation/docs-gluu-server-prod/
edit_uri: edit/3.1.0/3.1.0/source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.1.0'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '3.1.0': 'https://gluu.org/docs/gluu-server/3.1.0/'
    - '4.1': 'https://gluu.org/docs/gluu-server/4.1/'    
    - '4.0': 'https://gluu.org/docs/gluu-server/4.0/'  
    - '3.1.8': 'https://gluu.org/docs/gluu-server/3.1.8/'
    - '3.1.7': 'https://gluu.org/docs/gluu-server/3.1.7/'
    - '3.1.6': 'https://gluu.org/docs/gluu-server/3.1.6/'
    - '3.1.5': 'https://gluu.org/docs/gluu-server/3.1.5/'
    - '3.1.4': 'https://gluu.org/docs/gluu-server/3.1.4/'
    - '3.1.3.1': 'https://gluu.org/docs/gluu-server/3.1.3.1/'
    - '3.1.3': 'https://gluu.org/docs/gluu-server/3.1.3/'
    - '3.1.2': 'https://gluu.org/docs/gluu-server/3.1.2/'
    - '3.1.1': 'https://gluu.org/docs/gluu-server/3.1.1/'
    - 'EOL Versions': 'https://gluu.org/docs/eol'
- ' ': 'https://gluu.org/docs'
- ' ': 'https://gluu.org/docs'
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in 3.x: 'operation/intro.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
#        - 'Configuring Replication': 'installation-guide/cluster.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - Upgrade/Patch Guide:
#          - 'Upgrade Gluu Server' : 'upgrade/index.md'
#          - 'Upgrade Gluu Server with OpenDJ': 'upgrade/manual-update.md'
#        - 'Patch Gluu Server' : 'upgrade/update.md'
          - 'Updating a War File': 'upgrade/update-war.md'
- Administration Guide:
        - 'oxTrust admin UI' : 'admin-guide/oxtrust-ui.md'
        - 'Interception Scripts': 'admin-guide/custom-script.md'
        - User Authentication:
            - 'Introduction': 'authn-guide/intro.md'
            - 'Basic Authentication': 'authn-guide/basic.md'
            - 'Social Login': 'authn-guide/passport.md'
            - 'FIDO U2F': 'authn-guide/U2F.md'
            - 'Super Gluu': 'authn-guide/supergluu.md'
            - 'Duo Security': 'authn-guide/duo.md'
            - 'HOTP/TOTP': 'authn-guide/otp.md'
            - 'SMS OTP': 'authn-guide/sms-otp.md'
            - 'Certificate Authentication': 'authn-guide/cert-auth.md'
            - 'Google+ OAuth 2.0': 'authn-guide/google.md'
            - 'Account Lockout': 'authn-guide/lockout.md'
            - 'Custom Script Tutorial': 'authn-guide/customauthn.md'
        - 'Attributes' : 'admin-guide/attribute.md'
        - 'User Management' : 'admin-guide/user-management.md'
        - 'User Management with SCIM' : 'admin-guide/user-scim.md'
        - 'SCIM protected by UMA' : 'admin-guide/scim-uma.md'
        - 'SAML' : 'admin-guide/saml.md'
        #        - 'OAuth2 Grants' : 'admin-guide/oauth2.md'
        - 'OpenID Connect' : 'admin-guide/openid-connect.md'
        - 'UMA' : 'admin-guide/uma.md'
        - 'Session Management': 'admin-guide/session.md'
        - 'Central Authentication Service (CAS)' : 'admin-guide/cas.md'
        - 'Certificate Management' : 'admin-guide/certificate.md'
        - 'CORS Configuration' : 'admin-guide/cors.md'
- SSO Integration Guide:
        - 'Introduction': 'integration/index.md'
        - 'Server Side Web Apps':
            - 'oxd OAuth 2.0': 'integration/oxd-oauth2/index.md'
            - 'Nginx lua-resty-openidc': 'integration/sswebapps/nginx.md'
            - 'Apache mod_auth_openidc': 'integration/sswebapps/openidc-rp.md'
            - 'Shibboleth SAML SP': 'integration/sswebapps/saml-sp.md'
        - 'Single Page Apps':
            - 'Gluu OIDC JS Client': 'integration/spa/oauth-js-implicit.md'
            - 'Identity Model OIDC JS Client': 'integration/spa/identity-model-oidc-js-client.md'
        - 'Native Apps':
            - 'AppAuth iOS and macOS': 'integration/native-apps/appauth-ios.md'
            - 'AppAuth Android': 'integration/native-apps/appauth-android.md'
        - 'SaaS Integrations':
            - 'Google Apps': 'integration/saas/google.md'
            - 'Office 365': 'integration/saas/office.md'
            - 'Testing Shibboleth with TestShib2': 'integration/saas/testShib2.md'
#    - 'Hobsons Education Sol': 'integration/saas/hobsons.md'
            - 'Salesforce': 'integration/saas/salesforce.md'
            - 'Dropbox': 'integration/saas/dropbox.md'
            - 'GitHub Enterprise': 'integration/saas/github-enterprise.md'
            - 'Cisco WebEx': 'integration/saas/webex.md'
            - 'Amazon Web Services (AWS)': 'integration/saas/aws.md'
- Reference:
        - Gluu API Guide:
            - 'Custom ID Generation': 'api-guide/api.md'
            - 'OpenID Connect API': 'api-guide/openid-connect-api.md'
            - 'SCIM API Configuration': 'api-guide/scim-api.md'
            - 'UMA API': 'api-guide/uma-api.md'
        - 'JSON Properties':
            - 'OxTrust JSON Properties': 'reference/JSON-oxtrust-prop.md'
            - 'OxAuth JSON Properties': 'reference/JSON-oxauth-prop.md'
        - 'Gluu LDAP Schema':
            - 'Ox LDAP Properties': 'reference/oxldap.md'
            - 'OpenLDAP Schema': 'reference/schema.md'
- Operation Guide:
        - 'Patches': 'upgrade/patches.md'
        - 'Backups': 'operation/backup.md'
        - 'Find your Gluu Version': 'operation/find-gluu-version.md'
        - 'Ports': 'operation/ports.md'
        - 'Logout': 'operation/logout.md'
        - 'Log Management' : 'operation/logs.md'
        - 'Customize Public Pages': 'operation/custom-loginpage.md'
        - 'FAQ & Troubleshooting': 'operation/faq.md'
        - 'Change IP Address': 'operation/changeip.md'
        #       - 'Fine Tuning Gluu Server' : 'admin-guide/fine-tuning.md'
- Developer Guide:
        - 'Build oxTrust with Eclipse': 'developer-guide/oxtrust-eclipse.md'
- Tutorials:
        - 'Kafka Logging': 'tutorials/kafka.md'
        - 'Migrate OpenDJ to OpenLDAP': 'tutorials/migrate-opendj.md'
