# Project information
site_name: Gluu Server 3.1.3.1 Docs
site_description: Documentation for Gluu Server

# Copyright
copyright: Copyright &copy; 2020, Gluu, Inc.

# Repository
docs_dir: source
repo_name: GluuFederation/docs-gluu-server-prod
repo_url: https://github.com/GluuFederation/docs-gluu-server-prod/
edit_uri: edit/3.1.3.1/3.1.3.1/source

# Configuration
theme: 
    name: material
    palette:
        primary: 'green'
        accent: 'green'
    logo: 'gluu.jpg'
    favicon: 'favicon.ico'
extra:
    version: '3.1.3.1'

# Tracking
google_analytics:
  - 'UA-31008645-7'
  - 'auto'
  
# Extensions
markdown_extensions:
- admonition
- toc:
     permalink: '#'
- codehilite     
- pymdownx.superfences

# Navigation
nav:
- 'Versions':
    - '3.1.3.1': 'https://gluu.org/docs/gluu-server/3.1.3.1/'
    - '4.1': 'https://gluu.org/docs/gluu-server/4.1/'    
    - '4.0': 'https://gluu.org/docs/gluu-server/4.0/'    
    - '3.1.8': 'https://gluu.org/docs/gluu-server/3.1.8/'
    - '3.1.7': 'https://gluu.org/docs/gluu-server/3.1.7/'
    - '3.1.6': 'https://gluu.org/docs/gluu-server/3.1.6/'
    - 'EOL Versions': 'https://gluu.org/docs/eol'
- ' ': 'https://gluu.org/docs'
- ' ': 'https://gluu.org/docs'
- Home: 'index.md'
- Release Notes: 'release-notes/index.md'
- Whats new in v3: '3.1.x-intro.md'
- Installation Guide:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
        - 'Clustering': 'installation-guide/cluster.md'
- Administration Guide:
        - 'oxTrust admin UI': 'admin-guide/oxtrust-ui.md'
        - 'Interception Scripts': 'admin-guide/custom-script.md'
        - User Management:
            - 'Local User Management': 'user-management/local-user-management.md'
            - 'AD/LDAP Synchronization': 'user-management/ldap-sync.md'
            - 'SCIM 2.0 User Management': 'user-management/scim2.md'
            - 'SCIM new features': 'user-management/scim-new-features.md'
            - 'Replacing Expired JKS Files': 'user-management/replace-expired-jks-scim.md'
        - User Authentication:
            - 'Introduction': 'authn-guide/intro.md'
            - 'Basic Authentication': 'authn-guide/basic.md'
            - 'FIDO U2F': 'authn-guide/U2F.md'
            - 'Super Gluu': 'authn-guide/supergluu.md'
            - 'OTP apps': 'authn-guide/otp.md'
            - 'SMS OTP': 'authn-guide/sms-otp.md'
            - 'Passport Social': 'authn-guide/passport.md'
            - 'Passport Inbound SAML': 'authn-guide/inbound-saml-passport.md'
            - 'Passport Inbound OpenID Connect': 'authn-guide/inbound-oidc-passport.md'
            - 'Duo Security': 'authn-guide/duo.md'
            - 'ThumbSignIn': 'authn-guide/thumbsignin.md'
            - 'Certificate Authentication': 'authn-guide/cert-auth.md'
            #- 'Google+ OAuth 2.0': 'authn-guide/google.md'
            - 'Account Lockout': 'authn-guide/lockout.md'
            - 'Password Reset': 'authn-guide/pw-reset.md'
            - 'Custom Script Tutorial': 'authn-guide/customauthn.md'
            #- 'Inbound SAML using Asimba': 'authn-guide/inbound-saml-asimba.md'
        - 'Attributes': 'admin-guide/attribute.md'
        #- 'SCIM protected by UMA': 'admin-guide/scim-uma.md'
        - 'SAML IDP': 'admin-guide/saml.md'
        #        - 'OAuth2 Grants': 'admin-guide/oauth2.md'
        - 'OpenID Connect Provider (OP)': 'admin-guide/openid-connect.md'
        - 'UMA Authorization Server (AS)': 'admin-guide/uma.md'
        - 'Central Authentication Service (CAS)': 'admin-guide/cas.md'
        - 'Session Management': 'admin-guide/session.md'
        - 'Certificate Management': 'admin-guide/certificate.md'
        - 'CORS Configuration': 'admin-guide/cors.md'
- SSO Integration Guide:
        - 'Introduction': 'integration/index.md'
        - 'Server Side Web Apps':
            - 'oxd OAuth 2.0': 'integration/oxd-oauth2/index.md'
            - 'Nginx lua-resty-openidc': 'integration/sswebapps/nginx.md'
            - 'Apache mod_auth_openidc': 'integration/sswebapps/openidc-rp.md'
            - 'Shibboleth SAML SP': 'integration/sswebapps/saml-sp.md'
        - 'Single Page Apps':
            - 'AppAuth JS': 'integration/spa/appauth-js.md'
            - 'Gluu OIDC JS Client': 'integration/spa/oauth-js-implicit.md'
        - 'Native Apps':
            - 'AppAuth iOS and macOS': 'integration/native-apps/appauth-ios.md'
            - 'AppAuth Android': 'integration/native-apps/appauth-android.md'
        - 'SaaS / Off-the-shelf Apps':
            - 'Google Apps': 'integration/saas/google.md'
            - 'Office 365': 'integration/saas/office.md'
            - 'Moodle': 'integration/saas/moodle.md'
            - 'Salesforce': 'integration/saas/salesforce.md'
            - 'Dropbox': 'integration/saas/dropbox.md'
            - 'GitHub Enterprise': 'integration/saas/github-enterprise.md'
            - 'Cisco WebEx': 'integration/saas/webex.md'
            - 'Amazon Web Services (AWS)': 'integration/saas/aws.md'
            - 'TestShib2': 'integration/saas/testShib2.md'
- Reference:
        - Gluu API Guide:
            - 'Custom ID Generation': 'api-guide/api.md'
            - 'OpenID Connect API': 'api-guide/openid-connect-api.md'
            - 'SCIM API Configuration': 'api-guide/scim-api.md'
            - 'UMA API': 'api-guide/uma-api.md'
        - 'JSON Properties':
            - 'oxTrust JSON Properties': 'reference/JSON-oxtrust-prop.md'
            - 'oxAuth JSON Properties': 'reference/JSON-oxauth-prop.md'
        - 'Gluu LDAP Schema':
            - 'oxLDAP Properties': 'reference/oxldap.md'
            - 'LDAP Schema': 'reference/schema.md'
- Operation Guide:
        - 'Upgrades': 'upgrade/index.md'
        - 'Patches': 'upgrade/patches.md'
        - 'Backups': 'operation/backup.md'
        - 'Ports': 'operation/ports.md'
        - 'Logout': 'operation/logout.md'
        - 'Log Management' : 'operation/logs.md'
        - 'Customize Public Pages': 'operation/custom-design.md'
        - 'Change IP Address': 'operation/changeip.md'
        #- 'Find your Gluu Version': 'operation/find-gluu-version.md'
        #       - 'Fine Tuning Gluu Server' : 'admin-guide/fine-tuning.md'
- Developer Guide:
        - 'Build oxTrust with Eclipse': 'developer-guide/oxtrust-eclipse.md'
        - 'Localization': 'developer-guide/localization.md'
        - 'Script Debugging': 'developer-guide/script-debugging.md'
- Tutorials:
        - 'Kafka Logging': 'tutorials/kafka.md'
        - 'Migrate OpenDJ to OpenLDAP': 'tutorials/migrate-opendj.md'
- FAQ & Troubleshooting: 'operation/faq.md'
